version: "3"
services:
  vue-app:
    container_name: clinica-vue
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    ports:
      - 6000:6000