
services:
  vue:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 8050:5173

volumes:
  node_modules:

networks:
  aaip-dev:
    external: true